"use client";

import * as React from "react";
import { Check, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/shared/status-badge";
import { KeywordCoverage } from "./keyword-coverage";

const MAX_CHARS = 200;

const titleColorMap: Record<string, string> = {
  APPLIED: "bg-blue-500/15 text-blue-700 dark:text-blue-400 border-blue-500/25",
  ARCHIVED: "bg-zinc-500/15 text-zinc-500 border-zinc-500/25",
};

interface TitleCardProps {
  variant: {
    id: string;
    title: string;
    subtitle?: string | null;
    charCount: number;
    keywordsCovered: string[];
    keywordCount: number;
    trafficCovered: number;
    status: string;
    isActive: boolean;
    generatedBy: string;
    score?: number | null;
    aiReasoning?: string | null;
  };
  allKeywords?: string[];
  onApply?: (id: string) => void;
  applyLoading?: boolean;
  className?: string;
}

export function TitleCard({
  variant,
  allKeywords = [],
  onApply,
  applyLoading = false,
  className,
}: TitleCardProps) {
  const charPercent = Math.min(100, Math.round((variant.charCount / MAX_CHARS) * 100));
  const isNearLimit = variant.charCount > MAX_CHARS * 0.9;

  const uncovered = allKeywords.filter(
    (kw) => !variant.keywordsCovered.includes(kw)
  );

  const trafficTotal = 0;

  return (
    <Card className={cn("relative", variant.isActive && "ring-2 ring-emerald-500/40", className)}>
      {variant.isActive && (
        <div className="absolute top-3 right-3">
          <div className="flex items-center gap-1 rounded-full bg-emerald-500/15 px-2 py-0.5 text-xs font-medium text-emerald-600 dark:text-emerald-400">
            <Check className="size-3" />
            Active
          </div>
        </div>
      )}

      <CardHeader className="pb-3">
        <div className="flex items-start gap-2">
          <StatusBadge status={variant.status} colorMap={titleColorMap} size="sm" />
          {variant.score != null && (
            <span className="ml-auto text-sm font-mono font-medium text-muted-foreground">
              Score: {variant.score.toFixed(1)}
            </span>
          )}
        </div>
        <CardTitle className="text-base leading-relaxed break-words">
          {variant.title}
        </CardTitle>
        {variant.subtitle && (
          <p className="text-sm text-muted-foreground">{variant.subtitle}</p>
        )}
      </CardHeader>

      <CardContent className="space-y-4">
        <div className="space-y-1.5">
          <div className="flex items-center justify-between text-xs">
            <span className="text-muted-foreground">Characters</span>
            <span className={cn("font-mono", isNearLimit ? "text-amber-500" : "text-muted-foreground")}>
              {variant.charCount}/{MAX_CHARS}
            </span>
          </div>
          <div className="h-1.5 rounded-full bg-muted overflow-hidden">
            <div
              className={cn(
                "h-full rounded-full transition-all",
                isNearLimit ? "bg-amber-500" : "bg-primary",
              )}
              style={{ width: `${charPercent}%` }}
            />
          </div>
        </div>

        <KeywordCoverage
          covered={variant.keywordsCovered}
          uncovered={uncovered}
          percentage={
            (variant.keywordsCovered.length + uncovered.length) > 0
              ? Math.round(
                  (variant.keywordsCovered.length / (variant.keywordsCovered.length + uncovered.length)) * 100
                )
              : 0
          }
          trafficCovered={variant.trafficCovered}
          trafficTotal={trafficTotal > 0 ? trafficTotal : undefined}
          compact
        />

        <div className="flex items-center justify-between pt-1 text-xs text-muted-foreground">
          <span>Generated by: {variant.generatedBy}</span>
          <span>{variant.keywordCount} keywords</span>
        </div>

        {onApply && !variant.isActive && variant.status !== 'ARCHIVED' && variant.status !== 'REJECTED' && (
          <Button
            size="sm"
            variant="outline"
            className="w-full"
            onClick={() => onApply(variant.id)}
            disabled={applyLoading}
          >
            {applyLoading ? (
              <Loader2 className="mr-1 size-3.5 animate-spin" />
            ) : (
              <Check className="mr-1 size-3.5" />
            )}
            Apply Title
          </Button>
        )}
      </CardContent>
    </Card>
  );
}
