import { notFound } from 'next/navigation';
import Link from 'next/link';
import prisma from '@/lib/prisma';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table';
import { ArrowLeft, AppWindow, Check } from 'lucide-react';

const titleStatusStyle: Record<string, string> = {
  DRAFT: 'bg-zinc-500/20 text-zinc-400',
  APPROVED: 'bg-emerald-500/20 text-emerald-400',
  APPLIED: 'bg-blue-500/20 text-blue-400',
  REJECTED: 'bg-red-500/20 text-red-400',
  ARCHIVED: 'bg-zinc-700/40 text-zinc-500',
};

export default async function AppTitlesPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ page?: string }>;
}) {
  const { id } = await params;
  const sp = await searchParams;
  const page = Math.max(1, Number(sp.page) || 1);
  const limit = 20;

  const app = await prisma.app.findUnique({ where: { id }, select: { id: true, name: true } });
  if (!app) notFound();

  const [variants, total] = await Promise.all([
    prisma.titleVariant.findMany({
      where: { appId: id },
      skip: (page - 1) * limit,
      take: limit,
      orderBy: [{ score: 'desc' }, { createdAt: 'desc' }],
    }),
    prisma.titleVariant.count({ where: { appId: id } }),
  ]);

  const totalPages = Math.ceil(total / limit);

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon" asChild>
          <Link href={`/apps/${id}`}><ArrowLeft className="h-4 w-4" /></Link>
        </Button>
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Title Variants</h1>
          <p className="text-sm text-muted-foreground">{app.name} &middot; {total} variants</p>
        </div>
      </div>

      {variants.length > 0 ? (
        <Card className="border-border/50">
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow className="hover:bg-transparent">
                  <TableHead className="w-8"></TableHead>
                  <TableHead>Title</TableHead>
                  <TableHead>Subtitle</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Score</TableHead>
                  <TableHead className="text-right">Keywords</TableHead>
                  <TableHead className="text-right">Traffic</TableHead>
                  <TableHead>Generated By</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {variants.map((v) => (
                  <TableRow key={v.id}>
                    <TableCell>{v.isActive && <Check className="h-4 w-4 text-emerald-400" />}</TableCell>
                    <TableCell>
                      <div>
                        <p className="text-sm font-medium">{v.title}</p>
                        <p className="text-xs text-muted-foreground">{v.charCount} chars</p>
                      </div>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">{v.subtitle || '—'}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className={`border-transparent text-[11px] ${titleStatusStyle[v.status] || ''}`}>
                        {v.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right font-mono">{v.score?.toFixed(1) ?? '—'}</TableCell>
                    <TableCell className="text-right">{v.keywordCount}</TableCell>
                    <TableCell className="text-right">{v.trafficCovered.toLocaleString()}</TableCell>
                    <TableCell className="text-xs text-muted-foreground">{v.generatedBy}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      ) : (
        <Card className="border-border/50">
          <CardContent className="py-16 text-center">
            <AppWindow className="mx-auto mb-3 h-10 w-10 text-muted-foreground/50" />
            <p className="text-sm text-muted-foreground">No title variants yet</p>
            <p className="mt-1 text-xs text-muted-foreground/70">Title variants will be generated by the AI optimization engine</p>
          </CardContent>
        </Card>
      )}

      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2">
          <Button variant="outline" size="sm" disabled={page <= 1} asChild>
            <Link href={`/apps/${id}/titles?page=${page - 1}`}>Previous</Link>
          </Button>
          <span className="text-sm text-muted-foreground">Page {page} of {totalPages}</span>
          <Button variant="outline" size="sm" disabled={page >= totalPages} asChild>
            <Link href={`/apps/${id}/titles?page=${page + 1}`}>Next</Link>
          </Button>
        </div>
      )}
    </div>
  );
}
